# Generated by Django 3.2.25 on 2024-06-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
